export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO";
export const GET_PROYECTOS = "GET_PROYECTOS";
export const AGREGAR_PROYECTO = "AGREGAR_PROYECTO";
export const VALIDAR_FORMULARIO = "VALIDAR_FORMULARIO";
